### ISSUE TITLE
PS-GuiCompletion does not work in PowerShell Core 7.0 on Linux

### ISSUE THREAD

**Issue by COLAMAroro** [cspotcode/PS-GuiCompletion#13]
```txt
PS /mnt/c/Users/coren> Write-[TAB]An exception occurred in custom key handler, see $error for more information: Exception calling "GetBufferContents" with "1" argument(s): "The method or operation is not implemented."

PS /mnt/c/Users/coren> $ERROR

MethodInvocationException: /home/cola/.local/share/powershell/Modules/GuiCompletion/0.8.1/powertab/ConsoleLib.ps1:455
Line |
 455 |          $OldBuffer = $Host.UI.RawUI.GetBufferContents((New-Object Sys …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetBufferContents" with "1" argument(s): "The method or operation is not implemented."
```

**Comment by cspotcode** [comment]
Sadly, this can never work on Linux because Linux terminals do not allow read access of the console buffer, so `GetBufferContents` is not implemented.  `PS-GuiCompletion` reads the contents of the console, writes an overlay onto it, then erases the overlay by re-writing the original text to the same location on screen.  Linux terminals don't support the first step: reading the buffer.

On Linux, apps that implement this type of behavior -- curses, vim, etc -- do so by switching to the "alternate screen" and then maintaining the screen's state entirely in memory.   (that's the official name for it, as far as I can tell)

Similar functionality, such as the `Menucomplete` feature of PSReadLine, work around this limitation by writing several blank lines to the terminal, scolling everything upward and creating an empty region at the bottom of the screen.  They draw their "gui" into this empty region, knowing they can erase it entirely when they're done.

I don't work on this module anymore, but if someone else wanted to add Linux support, I would suggest that approach.  If anyone wants to do that work, I can add them as collaborators or move this repo to a neutral location.  Otherwise, I recommend using PSReadLine's `MenuComplete` feature.

**Comment by COLAMAroro** [comment]
A bit sad, but completely understandable

Thanks for your time and the detailed explanation !
