### ISSUE TITLE
Load on Powershell Start

### ISSUE THREAD

**Issue by Riot-Sec** [cspotcode/PS-GuiCompletion#2]
I am having trouble getting this to be the default config for Powershell.  Each time I launch powershell.exe I have to run "install-guicompletion -key tab"

Is there anyway to make this load automatically?

**Comment by cspotcode** [comment]
Yes, add that line to your PowerShell profile.  The quickest way to edit your profile is:

```
notepad $PROFILE
```

I chose this method of configuration because it is the same way you configure PSReadLine.  For example, here's an excerpt from my profile:

```
Set-PSReadLineKeyHandler -Key Ctrl+Spacebar -ScriptBlock { Invoke-GuiCompletion }
Set-PSReadLineKeyHandler -Key Tab -Function Complete
Set-PSReadLineOption -EditMode Vi
```

For more examples of configuring PSReadLine in your profile, you can check out their documentation: https://github.com/lzybkr/PSReadLine#usage

**Comment by Riot-Sec** [comment]
Thanks.

I like the Tab completion so "Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-GuiCompletion }" did it for me!
