### ISSUE TITLE
Configurable colors with less aggressive default, perhaps?

### ISSUE THREAD

**Issue by nightroman** [cspotcode/PS-GuiCompletion#5]
Is it or will it be possible to configure colors?

Regardless, is it possible to offer less "aggressive" default colors? I know,
this is a matter of personal taste. But many people are rather familiar with
sort of "standard" menu colors, see <kbd>F7</kbd> history menu in `cmd.exe`
console. Why not use it as the default?

**Comment by cspotcode** [comment]
Yes, it's currently possible to configure the colors using the `$GuiCompletionConfig` variable.  The defaults come from [PowerTab's "original" theme](https://powertab.codeplex.com/SourceControl/latest#ColorThemes/ThemeOriginal.csv).  PowerTab has about a dozen different color themes and a command to switch between them.  I didn't have time to incorporate them into this project, but it should be a simple matter of copy-pasting the code.

Alternatively, adding a paragraph of documentation about `$GuiCompletionConfig` to the README would be very helpful to new people.

I don't have time to make changes at the moment due to work and other projects taking my time.  However, if anyone would like to send a pull request or even become a collaborator, let me know and I'll grant you access.

**Comment by nightroman** [comment]
The PR is sent. Known caveats:

(1) In the PowerShell console coming with Windows DarkMagenta for some reason
is the same color as the console background color, the famous "noble blue".
It's their weird decision, IMHO. As a result, the menu actually uses that
color. It turns out to be not bad, distinctive, as they wanted.

But in the standard cmd console with PowerShell (or default colors restored)
the scheme prints menus similar to cmd menus. I think this is good for the
default scheme.

(2) I used `FilterColor = 'DarkGray'`. I would probably use DarkMagenta as
the default, too. But it turns out this color is used for both the top menu
line and the command line. As a result, in *Windows* PowerShell console it
prints blue on blue in the command line, i.e. not visible text. So I use
DarkGray instead, visible in both places.

Eventually, we should have two configurable colors: one for the top menu line
and another for the command line.
